### ISSUE TITLE
Error in "makerboard create my7688"

### ISSUE THREAD

**Issue by owenchen** [cfsghost/makerboard#3]
We ran install instruction step by step. After we ran "makerboard create my7688", the screen shown 

/usr/local/lib/node_modules/makerboard/lib/container.js:256
        co(function *() {
                    ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/makerboard/lib/makerboard.js:4:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by cfsghost** [comment]
You must use Node.js 0.12+ which supported Generator function.
