### ISSUE TITLE
Failed to run create command

### ISSUE THREAD

**Issue by alwint3r** [cfsghost/makerboard#4]
Hi,

I encountered this error when running command:
`makerboard create my7688`
And here's the error stack:

```
fs.js:844
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/usr/lib/node_modules/makerboard/data'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/makerboard/lib/downloader.js:31:18)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:430:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
```

I am using elementary os freya (ubuntu 14.04) and have npm v3.10, node v4.4.7, and qemu utility installed.

Thanks

**Comment by joerg-krause** [comment]
Did you install the npm package globally using the `-g` flag?

**Comment by alwint3r** [comment]
Yes, i got this output after running `npm ls -g --depth=0 | grep makerboard` command:

```
├── makerboard@0.1.8
```

**Comment by joerg-krause** [comment]
Does your npm install the global packages into `/usr/lib/node_modules`? Can you check with:
`ls -l /usr/lib/node_modules`.

**Comment by alwint3r** [comment]
Yes, the package is there. Here's the output that's piped to `grep makerboard`:

```
drwxr-xr-x  8 nobody dycode 4096 Jul 21 10:20 makerboard
```

**Comment by popk** [comment]
I tried this before npm install 

`sudo chown -R $USER /usr/local/lib/node_modules
`

And it works.!

**Comment by RyanM19920** [comment]
Created a blank folder named "data" in the "makerboard" directory.  Worked fine after that.
