### ISSUE TITLE
npm ERR! Error: CERT_UNTRUSTED

### ISSUE THREAD

**Issue by hitfzyangdianshi** [cfsghost/makerboard#7]
when installing by " npm install -g makerboard", i got this error info:

npm http GET https://registry.npmjs.org/makerboard
npm http GET https://registry.npmjs.org/makerboard
npm http GET https://registry.npmjs.org/makerboard
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-25-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "makerboard"
npm ERR! cwd /home/qwer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/qwer/npm-debug.log
npm ERR! not ok code 0

**Comment by hitfzyangdianshi** [comment]
npm.debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'makerboard' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose cache add [ 'makerboard', null ]
5 verbose cache add name=undefined spec="makerboard" args=["makerboard",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'makerboard',
6 verbose parsed url   path: 'makerboard',
6 verbose parsed url   href: 'makerboard' }
7 silly lockFile b45f0f26-makerboard makerboard
8 verbose lock makerboard /home/qwer/.npm/b45f0f26-makerboard.lock
9 silly lockFile b45f0f26-makerboard makerboard
10 silly lockFile b45f0f26-makerboard makerboard
11 verbose addNamed [ 'makerboard', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile ffc3bb06-makerboard makerboard@
14 verbose lock makerboard@ /home/qwer/.npm/ffc3bb06-makerboard.lock
15 silly addNameRange { name: 'makerboard', range: '*', hasData: false }
16 verbose url raw makerboard
17 verbose url resolving [ 'https://registry.npmjs.org/', './makerboard' ]
18 verbose url resolved https://registry.npmjs.org/makerboard
19 info trying registry request attempt 1 at 02:47:38
20 http GET https://registry.npmjs.org/makerboard
21 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
22 info trying registry request attempt 2 at 02:47:48
23 http GET https://registry.npmjs.org/makerboard
24 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
25 info trying registry request attempt 3 at 02:48:48
26 http GET https://registry.npmjs.org/makerboard
27 silly lockFile ffc3bb06-makerboard makerboard@
28 silly lockFile ffc3bb06-makerboard makerboard@
29 error Error: CERT_UNTRUSTED
29 error     at SecurePair.<anonymous> (tls.js:1370:32)
29 error     at SecurePair.EventEmitter.emit (events.js:92:17)
29 error     at SecurePair.maybeInitFinished (tls.js:982:10)
29 error     at CleartextStream.read [as _read] (tls.js:469:13)
29 error     at CleartextStream.Readable.read (_stream_readable.js:320:10)
29 error     at EncryptedStream.write [as _write] (tls.js:366:25)
29 error     at doWrite (_stream_writable.js:223:10)
29 error     at writeOrBuffer (_stream_writable.js:213:5)
29 error     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
29 error     at write (_stream_readable.js:583:24)
30 error If you need help, you may report this log at:
30 error     <http://github.com/isaacs/npm/issues>
30 error or email it to:
30 error     <npm-@googlegroups.com>
31 error System Linux 3.19.0-25-generic
32 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "makerboard"
33 error cwd /home/qwer
34 error node -v v0.10.25
35 error npm -v 1.3.10
36 verbose exit [ 1, true ]

**Comment by hitfzyangdianshi** [comment]
one potential solution:   

https://stackoverflow.com/questions/21855035/ssl-error-cert-untrusted-while-using-npm-command

**Comment by hitfzyangdianshi** [comment]
https://stackoverflow.com/questions/21855035/ssl-error-cert-untrusted-while-using-npm-command
